name: assignment6
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: any
  path: any
  audioplayers: ^6.0.0
  permission_handler: ^10.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: ^0.19.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/big_img/
    - assets/small_img/
    - assets/mp3/
    - assets/logo.jpeg

  fonts:
    - family: FjallaOne
      fonts:
        - asset: assets/fonts/FjallaOne-Regular.ttf
